name 'kodius_cookbook'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures kodius_cookbook'
long_description 'Installs/Configures kodius_cookbook'
version '0.1.0'
depends 'nodejs', '~> 6.0.0'
depends 'application_javascript', '~> 1.0.0'
depends 'application_git', '~> 1.2.0'
